// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00U3u2d460IoRPi8zh8TKg-rlwQGNyJ4',
    appId: '1:875098261589:web:46edf719f1c0fc7f3cecdc',
    messagingSenderId: '875098261589',
    projectId: 'xemtro',
    authDomain: 'xemtro.firebaseapp.com',
    storageBucket: 'xemtro.appspot.com',
    measurementId: 'G-H8DSYTFVW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdYdMiOSLF4w55Ks7E1-CZ-5iJlsXmE8',
    appId: '1:875098261589:android:493370059f0fb8d73cecdc',
    messagingSenderId: '875098261589',
    projectId: 'xemtro',
    storageBucket: 'xemtro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKnK1dMdlgrnD82eMu4vCKCIUCJgED3XY',
    appId: '1:875098261589:ios:0e6a59b1b8590f153cecdc',
    messagingSenderId: '875098261589',
    projectId: 'xemtro',
    storageBucket: 'xemtro.appspot.com',
    iosBundleId: 'com.example.adminAppXemTro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKnK1dMdlgrnD82eMu4vCKCIUCJgED3XY',
    appId: '1:875098261589:ios:9c9412d1cb6bda263cecdc',
    messagingSenderId: '875098261589',
    projectId: 'xemtro',
    storageBucket: 'xemtro.appspot.com',
    iosBundleId: 'com.example.adminAppXemTro.RunnerTests',
  );
}
